
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 01 21:35:28 CST 2021
//----------------------------------------------------

package C3D;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POT = 30;
  public static final int PI = 45;
  public static final int EXPR = 12;
  public static final int PD = 46;
  public static final int CONTINUE = 20;
  public static final int INCR = 23;
  public static final int FOR = 22;
  public static final int IDENTIFICADOR = 47;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int MENORIGUAL = 39;
  public static final int IGUAL = 41;
  public static final int ELSEIF = 16;
  public static final int AGRUPACION = 27;
  public static final int OR = 43;
  public static final int IN = 8;
  public static final int CC = 5;
  public static final int IF = 13;
  public static final int CA = 4;
  public static final int MAYORIGUAL = 40;
  public static final int EOF = 0;
  public static final int ASIG = 26;
  public static final int RETURN = 25;
  public static final int error = 1;
  public static final int DIGITO = 48;
  public static final int DIF = 31;
  public static final int COMENTARIO = 28;
  public static final int MENOS = 33;
  public static final int MENOR = 37;
  public static final int MOD = 36;
  public static final int DIGITODECIMAL = 49;
  public static final int BREAK = 21;
  public static final int EQ = 6;
  public static final int ERROR = 29;
  public static final int SWITCH = 17;
  public static final int MAYOR = 38;
  public static final int LLC = 3;
  public static final int PUTS = 11;
  public static final int LLA = 2;
  public static final int ELSE = 15;
  public static final int WHILE = 19;
  public static final int NI = 9;
  public static final int DEFAULT = 18;
  public static final int THEN = 14;
  public static final int NE = 7;
  public static final int PROC = 24;
  public static final int DIVISION = 35;
  public static final int SET = 10;
  public static final int MULTIPLICACION = 34;
  public static final int MAS = 32;
}

